### ISSUE TITLE
Contao 4.8.7 Argument 2 passed to Contao\Controller:getTemplateGroup

### ISSUE THREAD

**Issue by Heinz3000** [ContaoDMS/dms#53]
ContaoDMS neu installiert über Contaomanger
Dateityp doc und docs angelegt.
Beim Versuch die FrontendModule anzulegen kann diese Fehlermeldung.

Argument 2 passed to Contao\Controller::getTemplateGroup() must be of the type array, string given, called in /var/cache/prod/contao/dca/tl_module.php on line 1949

**Comment by cliffparnitzky** [comment]
Kann du diese Datei `/var/cache/prod/contao/dca/tl_module.php` mal per FTP downloaden und hier anhängen`?

**Comment by Heinz3000** [comment]
Hier ist die tl_module.php
MfG Heinz
[tl_module.txt](https://github.com/ContaoDMS/dms/files/3975816/tl_module.txt)

**Comment by Heinz3000** [comment]
var/cache/prod/contao/dca/tl_module.php on line 2364

**Comment by cliffparnitzky** [comment]
Ja, eindeutig ein Fehler. Scheint noch aus Contao 2 Zeiten zu sein.

Hier muss die `$intPid` raus: https://github.com/ContaoDMS/dms/blob/master/system/modules/DocumentManagementSystem/dca/tl_module.php#L122

**Comment by cliffparnitzky** [comment]
Bitte man auf 3.2.3 updaten. Sollte damit behoben sein.

**Comment by Heinz3000** [comment]
Ist  behoben. Vielen Dank
MfG Heinz
